# visit https://github.com/mojombo/jekyll/wiki/Configuration for more settings

url:                 http://bobbelderbos.com
baseurl:             ""

paginate: 10 # pagination based on number of posts
paginate_path: "page:num"
exclude: ["README.md"] # files to exclude
highlighter: rouge
markdown: kramdown
disqus: bbelderbos
google_analytics: UA-11978104-1

defaults:
  -
    scope:
      path: "" # empty string for all files
    values:
      title: Bob Belderbos
  -
    scope:
      path: ""
      type: "posts"
    values:                                                                                                                                                              
      permalink: /:year/:month/:title/

description: I build useful apps and share my learning
fbgroup: https://www.facebook.com/groups/1305028816183522
author:
  name: Bob Belderbos
  email: info@bobbelderbos.com
  github: bbelderbos
  twitter: bbelderbos
  pinterest: bbelderbos
  linkedin: bbelderbos
  bio: I build useful apps and share my learning
  email_md5: e1d159796a39ce2eafe4b40e9b8f9871

rss_path: feed.xml
categories_path: categories.html
tags_path: tags.html

# set it as url of an image
sidebar_background_image: https://dl.dropboxusercontent.com/u/5798664/binary_wallpaper.jpg
#https://www.dropbox.com/s/g9h23zrycedxtk5/sky.png?raw=1

BASE_PATH:

gems:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-crosspost-to-medium
